### ISSUE TITLE
CHsplits will not change songs when skipping a song in a playlist

### ISSUE THREAD

**Issue by Cens0rs** [Tornith/CHSplit#11]
**Describe the bug**
When playing a playlist, if you skip the current song, chsplits will not change the song and will keep the splits and song title of the previous song in the playlist. Interestingly enough, it will update the score back to 0.

**To Reproduce**
1. Create a playlist with at least 2 songs
2. play the playlist
3. pause and hit "Skip Song"
4. See that the splits did not update

**Expected behavior**
If you skip the current song in a playlist, it should update the splits to the next song in the playlist.

**Screenshots**
![before](https://user-images.githubusercontent.com/33385351/76154867-909e6900-60b1-11ea-8682-72769237cba2.png)
![after](https://user-images.githubusercontent.com/33385351/76154868-9300c300-60b1-11ea-97eb-df0047227eac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 v1903
 - CPU: I7 6700k
 - GPU: rtx 2060
 - Clone Hero version 23.2.2
 - CHSplit Version 0.2.1
 - No modifications installed.

**Additional context**
If you continue playing the next song, it still doesn't update the splits. I found that to temporarily fix the issue and to force chsplits to update to the current song, you have to close chsplits and reopen it.
![continue playing](https://user-images.githubusercontent.com/33385351/76154951-25559680-60b3-11ea-80f1-3fd3657fa892.png)

**Logs**
[latest.log](https://github.com/Tornith/CHSplit/files/4302709/latest.log)

**Comment by Tornith** [comment]
Fixed in the upcoming update
