### ISSUE TITLE
Save runs

### ISSUE THREAD

**Issue by ModestSkillsCH** [Tornith/CHSplit#2]
Every time CH Split is closed and relaunched, there is no PB to go against, it is completely fresh, is there a way to save the runs, so they can be ran against in the future even when ch split is closed and launched again.

**Comment by Tornith** [comment]
CHSplit should save your runs, my guess it's related to the random modifiers bug

**Comment by ModestSkillsCH** [comment]
yeah when i use ch modifiers it doesnt save my run, like the WT mod,
without the mod ch split saves the runs.
Thanks for the info

**Comment by Tornith** [comment]
Should now be resolved in v0.2.1
