### ISSUE TITLE
CH Split v0.2.1 Speed % Problem

### ISSUE THREAD

**Issue by MatharuG** [Tornith/CHSplit#4]
Hello!
I saved the CHSplit's files in my Dropbox, so I can have the same scores on my Notebook.
But when playing it, it doesn't load the already existing Scores, instead, it creates a new file of the same song, but with an ABSURD amount of speed (even when playing at Normal Speed)

![2020-02-13 10_29_10-CHSplit](https://user-images.githubusercontent.com/26250877/74441368-71177600-4e4e-11ea-9f81-83e50f7380fe.png)

Thanks!

**Comment by Tornith** [comment]
Yeah, I know about this issue, it happens very rarely, usually just a restart of CH (or your entire laptop/PC) works but if this persists even after then please let me know

**Comment by MatharuG** [comment]
Well…
It persisted even after restarting CH and after restarting the laptop.
But this time with a different number… (13%) (Don't have the screenshot now -_-)


Edit (02/14/2020): TBH The best thing I can do is reinstall/re-extract the program; NOT put it in Dropbox, and see if it works

Edit 2 (02/15/2020): Re-extracting the program didn't work. And it's a different number again. This time it was (14%). On the Dropbox Version, I still get the same number as the 1st time.

**Comment by MatharuG** [comment]
Well, I discovered the issue
CHSplit doesn't like the now not-supported Windows 7.
After updating to Windows 10 v1909 (I was going to do that anyway), I don't have any weird %Speeds

In the Dropbox side of things, CHSplit doesn't like being shared in the cloud...

**LOCKED AND LOADED**

**Comment by MatharuG** [comment]
> 
> 
> Well, I discovered the issue
> CHSplit doesn't like the now not-supported Windows 7.
> After updating to Windows 10 v1909 (I was going to do that anyway), I don't have any weird %Speeds
> 
> In the Dropbox side of things, CHSplit doesn't like being shared in the cloud...
> 
> **LOCKED AND LOADED**


SIKE!
In the Laptop side of things, it's all normal. On the PC side of things, the crazy numbers are back.
Already installed v0.2.1, and restarted my PC

[latest.log](https://github.com/Tornith/CHSplit/files/4209236/latest.log)

**Comment by MatharuG** [comment]
Sike again
CHSplit is now very friendly in Dropbox
Don't know what I did.
Just reinstalled everything, and changed the settings to my preferences, but kept the Light Theme
Don't know if the Light Theme was the problem

**LOCKED AND LOADED FOR REAL THIS TIME**
