### ISSUE TITLE
Incorrect song labels in CHSplit

### ISSUE THREAD

**Issue by Davey-Dev** [Tornith/CHSplit#5]
Hard to explain this bug so I'd rather just show, not shown in video link but it happens with all songs

Don't exactly know what caused it but I had just rebooted my PC beforehand

Unlisted Video Link: https://youtu.be/V4wzZSC8TMY

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU: Intel Core I7 8700
 - Clone Hero version: 23.2.2
 - CHSplit Version: 0.2
 - Any modifications to Clone Hero: GH3 Texture Mod, however CHSplit has worked perfectly with the texture mod before 

[latest.log](https://github.com/Tornith/CHSplit/files/4201846/latest.log)
Log file data is the same session as the recording

**Comment by Tornith** [comment]
Should now be resolved in v0.2.1
