### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by SnakemanUltra7** [Tornith/CHSplit#9]
Every time i try to install it it fir
st says network error then i restart it and then it says forbidden. Help

![How to take a screenshot on a PC or Laptop any Windows - YouTube - Google Chrome 3_1_2020 3_45_37 PM (2)](https://user-images.githubusercontent.com/61668021/75635608-a6ed8600-5bd4-11ea-8739-b38a36b2c930.png)

![Uploading How to take a screenshot on a PC or Laptop any Windows - YouTube - Google Chrome 3_1_2020 3_45_26 PM (2).png…]()

**Comment by Tornith** [comment]
Sounds like issues on your side, could be your antivirus not liking it or your internet just being unstable
